// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectSchool.Data;

#nullable disable

namespace ProjectSchool.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20250606062934_UpdateFix")]
    partial class UpdateFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("KlassenraumSchueler", b =>
                {
                    b.Property<int>("KlassenraumId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchuelerImRaumId")
                        .HasColumnType("INTEGER");

                    b.HasKey("KlassenraumId", "SchuelerImRaumId");

                    b.HasIndex("SchuelerImRaumId");

                    b.ToTable("KlassenraumSchueler", (string)null);
                });

            modelBuilder.Entity("ProjectSchool.Models.Klassenraum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCynap")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Plaetze")
                        .HasColumnType("INTEGER");

                    b.Property<float>("RaumInQm")
                        .HasColumnType("REAL");

                    b.Property<int>("SchuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SchuleId");

                    b.ToTable("Klassenraeume", (string)null);
                });

            modelBuilder.Entity("ProjectSchool.Models.Schueler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Alter")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Geburtstag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Geschlecht")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Klasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SchuleId");

                    b.ToTable("Schueler", (string)null);
                });

            modelBuilder.Entity("ProjectSchool.Models.Schule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Schulen", (string)null);
                });

            modelBuilder.Entity("KlassenraumSchueler", b =>
                {
                    b.HasOne("ProjectSchool.Models.Klassenraum", null)
                        .WithMany()
                        .HasForeignKey("KlassenraumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectSchool.Models.Schueler", null)
                        .WithMany()
                        .HasForeignKey("SchuelerImRaumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectSchool.Models.Klassenraum", b =>
                {
                    b.HasOne("ProjectSchool.Models.Schule", null)
                        .WithMany("KlassenraumList")
                        .HasForeignKey("SchuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectSchool.Models.Schueler", b =>
                {
                    b.HasOne("ProjectSchool.Models.Schule", null)
                        .WithMany("SchuelerList")
                        .HasForeignKey("SchuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectSchool.Models.Schule", b =>
                {
                    b.Navigation("KlassenraumList");

                    b.Navigation("SchuelerList");
                });
#pragma warning restore 612, 618
        }
    }
}
